# Generated by Django 4.1.7 on 2023-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecategory',
            name='color',
            field=models.CharField(choices=[('#C70039', 'red'), ('#0096FF', 'blue'), ('#FFFFFF', 'white'), ('#848484', 'gray'), ('#6A00DF', 'purple'), ('#00A131', 'green'), ('#FFC300', 'yellow')], max_length=7, verbose_name='Цвет списка'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='profilecategory',
            order_with_respect_to='profile',
        ),
    ]
